name: DevSecOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build scanner-panel image
        run: docker build -t scanner-panel:test ./scanner-panel

      - name: Run Trivy SCA on scanner-panel
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scanner-panel:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: reports/
